### ISSUE TITLE
Island Top Signs

### ISSUE THREAD

**Issue by xXSKILLS2015Xx** [tastybento/askyblockIssues#778]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Spigot 1.8.8
**Plugin version:**
AcidIsland V3.0.8.8
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
Neither
**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
Not needed for the report
**Description of issue. What happened?**
I don't know how to make Island Top Signs for AcidIsland. I looked it up but found nothing on it. If there are no signs for it is there an available add-on that I can use for this? Maybe LeaderHeads?
**Steps to make this happen**

1. N/A

**What do you think should happen?**
I would like this to be implemented into the AcidIsland and ASkyBlock plugins. # #

**Comment by tastybento** [comment]
Maybe this one? https://www.spigotmc.org/resources/toptenheads-for-acidisland.26752/
