### ISSUE TITLE
restrictwither should include tnt and falling blocks

### ISSUE THREAD

**Issue by TheWranger** [tastybento/askyblockIssues#793]
I think restrictwither should also restrict primed tnt and falling blocks as these entities, similarly to blazes, ghasts and withers, can effect other peoples islands.

**Comment by tastybento** [comment]
Can you explain more?

**Comment by TheWranger** [comment]
Redstone contraptions could be used to move falling block entities or tnt entities out of an island. Considering `restrictwither` seems to have the purpose of stopping entities from one island impacting another, I think it should also stop falling blocks and primed tnt.
