### ISSUE TITLE
Invincible visitors still receiving fall damage

### ISSUE THREAD

**Issue by TheWranger** [tastybento/askyblockIssues#875]
**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Paper 1506 (1.12.2)
**Plugin version:**
Acidisland V3.0.9.3
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
Upgrade form 3.0.9.1
**Description of issue. What happened?**
Visitors are still receiving fall damage outside of their island, despite plugin being configured to block this.
```   # Invincible visitors - Prevent players from killing them (intentionally or by accident)
   # If they fall to the void, they get TP'd to their island.
   invinciblevisitors: true
   
   # Only used if invinciblevisitors is set to TRUE
   # This allow you to customize what kind of damage visitors should not receive
   # If you want visitors to receive a listed damage, put a "#" at the start of the line
   # See this for more info about options : https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
   invinciblevisitorsoptions:
   - BLOCK_EXPLOSION
   - CONTACT
   - CUSTOM
   - ENTITY_ATTACK
   - ENTITY_EXPLOSION
   - ENTITY_SWEEP_ATTACK
   - FALL
   - FALLING_BLOCK
   - FIRE
   - FIRE_TICK
   - LAVA
   - MAGIC
   - POISON
   - PROJECTILE
   - SUFFOCATION
   - THORNS
   - WITHER
   # 1.9+ only
   - DRAGON_BREATH
   - FLY_INTO_WALL
   # 1.10+ only
   - HOT_FLOOR
   # 1.11+ only
   - CRAMMING
```
**Steps to make this happen**

1. Go outside island
2. Try to take fall damage.

**What do you think should happen?**
Visitors should receive fall damage.

**Comment by TheWranger** [comment]
I believe this also affects CUSTOM damage as well.

**Comment by Malachiel87** [comment]
i confirm the issue, visitors receive falling damage 1,8.9, and 3.0.9.4 askyblock

**Comment by TheWranger** [comment]
@tastybento any news on a fix for this? Is a pretty large issue

**Comment by Poslovitch** [comment]
ASkyBlock support is dropped. Read README.

**Comment by Malachiel87** [comment]
so we have to costrict all user to live with that bug, and wait a converter for go into bentobox?

**Comment by Poslovitch** [comment]
Yes.

**Comment by Malachiel87** [comment]
any eta about the converter?

**Comment by Poslovitch** [comment]
No, that's planned, that's it. We cannot provide an ETA for BBox as long as BBox is not even released.

**Comment by ygtdmn** [comment]
Problem solved with this: https://github.com/tastybento/askyblock/pull/714
