### ISSUE TITLE
Colored text on signs automatically

### ISSUE THREAD

**Issue by iTommyB** [tastybento/askyblockIssues#919]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Paper version git-Paper-1555 (1.12.2

**Plugin version:**
3.0.9.4 (LATEST)

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
New install

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
Plugins (56): AdvancedPortals, AdvancedRepair, ASkyBlock, AutoRestart, BlockCreator, BuycraftX, ChatColorPlus, ChatReaction, Citizens, ClearLag, CommandNPC, CommandSpy, CrazyAuctions, CustomOreGen, DailyRewards, DeluxeTags, EasyBackup, EnhancedBalTop, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit, FeatherBoard, GroupManager, HolographicDisplays, IPWhitelist, KitsCreator, MessageAnnouncer, MiniaturePets, Minions, Multiverse-Core, MVdWPlaceholderAPI, MyCommand, NametagEdit, NightVisionReloaded, OldCombatMechanics, OpenInv, PlaceholderAPI, PlayerVaults, PlugMan, ProtocolSupport, Shop, ShopGUIPlus, SilkSpawners, SimpleRename, StackMob, StaffChat, SuperTrails, TimeLock, TitleManager, TradePlus, Vault, VoidSpawn, WorldEdit, WorldGuard, XPBoost

**Description of issue. What happened?**
If you are default and place a sign with text, the signs default colored text is white, and if you are operator, the signs default color is light_green.

**Steps to make this happen**

1. Place a sign with whatever text on whatever line.
2. Click done
3. And there you go.

**What do you think should happen?**
Look into why it might not work, and update on why it doesn't.

**Comment by tastybento** [comment]
I don't understand. Sign text is usually black. The plugin doesn't mess with sign colors.
