### ISSUE TITLE
Player can't break or place blocks

### ISSUE THREAD

**Issue by NectorYT** [tastybento/askyblockIssues#920]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Bukkit 1.12.2

**Plugin version:1.12

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?new install

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here): WorldEdit, ArenaPVP, CrazyCrates, MyPrefixSystem, OpenInv, GroupManager, ClearLag, MenuReport, ChatControl, SetSpawn, GuiCreationTool, LaggRemover, HeadDrops, PexTabListPlus, CategoryWarps, LobbyCompass, StaffChat, Vault, SellChest, Greenhouses, Essentials, AcidIsland, Multiverse-Core, KitAdder, Citizens, EssentialsProtect, EssentialsChat, EssentialsGeoIP, EssentialsAntiBuild, AddLight, RedProtect, HolographicDisplays

**Description of issue. What happened?**
When Players create an Island they can't break or place blocks and can't open chests
**Steps to make this happen**

1. 
2.
3.

**What do you think should happen?**
Should I answer this? xD

**Comment by Rengobli** [comment]
Hey,
I am pretty sure this has nothing to do with aSkyBlock.
Please make sure that players are allowed to place/break blocks.

Plugins that would prevent this (on your list, as far as I know):
- WorldGuard
- EssentialsProtect
- EssentialsAntiBuild

Try to uninstall this plugin(s) and try it again. By using this step(s), you will be able to filter out your problem.
