### ISSUE TITLE
Offline/Online UUID inssue

### ISSUE THREAD

**Issue by Zarpyk** [tastybento/askyblockIssues#921]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
1.9 Spigot
**Plugin version:**
3.0.9.4
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
Upgrade, 3.0.9
**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
...
DynamicBungeeAuth
...
**Description of issue. What happened?**
The DynamicBungeeAuth have /premium, and it convert the offline uuid to premium uuid and if the player don't put this command on join, he lost he Island
**Steps to make this happen**

1. Join using offline uuid
2. Create island
3. Switch to premium uuid
4. Join to the server

**What do you think should happen?**
Remove the offline uuid and set the online uuid
(Now I need close completly the server and chance uuid manualy, but if I have to do this every time it happens, is very annoying for the players)

**Comment by tastybento** [comment]
Sorry, there's nothing I can do about this because we use UUID's for everything. If a UUID changes then it's just like another player.
