### ISSUE TITLE
allowvisitoritempickup

### ISSUE THREAD

**Issue by Lablador** [tastybento/askyblockIssues#922]
allowvisitoritempickup: false  
not working how can i solve it?
Spigot : 1.8.x
Wg : worldguard-6.1.jar
ASkyBlock Jar : V3.0.9.4 
Config : https://hastebin.com/lohutajinu.php

**Comment by tastybento** [comment]
If this is a recent change, then you need to flush the settings using /asadmin settingsreset all.
