### ISSUE TITLE
islands upgrades

### ISSUE THREAD

**Issue by Nicholashefner** [tastybento/askyblockIssues#925]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**spigot 1.8.8? 

**latest**

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?** new

using luckperms

**when people purchase an island size upgrade, the size works but as soon as the relog/ quit then rejoin it resets back to default**

it should stick why doesnt it

**Comment by tastybento** [comment]
What permissions do they have exactly?
