### ISSUE TITLE
[Important] Is go kill player

### ISSUE THREAD

**Issue by Zarpyk** [tastybento/askyblockIssues#929]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Spigot 1.9.4
**Plugin version:**
3.0.9.4
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
Upgrade, 3.0.9
**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**

**Description of issue. What happened?**
Player go to island and kill
**Steps to make this happen**

1. I don't know, this only just happens whit one player
2. https://bit.ly/2Q0wpVD
3.

**What do you think should happen?**
I think the player was killed by falling damage

**Comment by Zarpyk** [comment]
Ok... is not only one plyer happens it, is all players, but sometime it kill they and sometime not

**Comment by Rengobli** [comment]
Did you seriously but a bit.ly link into a support section.. lol

**Comment by Zarpyk** [comment]
> Did you seriously but a bit.ly link into a support section.. lol

bit.ly is a url shortener :v is no adfly...

**Comment by tastybento** [comment]
The link doesn't work and I don't understand your bug report, sorry.
