### ISSUE TITLE
[Help / suggestion / support]

### ISSUE THREAD

**Issue by Golicraft** [tastybento/askyblockIssues#932]
Hi there lovely devs. I am wondering if it is possible to make an option to enable water in The Nether? 

When I try to place water it says "Island biome set to Nether!"

I have tried many plugins that support making water in The Nether but ASkyBlock seems to overwrite it. 

Best Regards,
Goli

**Comment by tastybento** [comment]
Sorry, yes, it's blocked and we're not working on ASB anymore. If you know a dev, they can fork the code and probably make it work. There is water in the nether with BentoBox's AcidIsland. That's our next plugin.
