### ISSUE TITLE
Island level 

### ISSUE THREAD

**Issue by NectorYT** [tastybento/askyblockIssues#933]
Hi this is not exactly a bug report but I wanted to ask how to put island level next to names like             
(500) NectorYT

pls respond!

**Comment by Golicraft** [comment]
I can help you out.

In essentialsChat and Essentials config you can have the placeholder:
  format: '&8{ISLAND_LEVEL} {DISPLAYNAME} &f{MESSAGE}'
{island_level} is the placeholder that is going to be replaced with the island level.

:)
