### ISSUE TITLE
Skyblock - tickEntities 

### ISSUE THREAD

**Issue by justinbea** [tastybento/askyblockIssues#951]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Spigot 1.12.2  (324 versions behind)

**Plugin version:**
3.0.9.4

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
new install

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
StaffMonitor, PlaceholderAPI, CustomRecipes, Arconix, Minions, CraftingStore, SuperWelcome, StaffPlus, TopLite, CoreProtect, FastCraft, OpenInv, HackedServer, MessageAnnouncer, Votifier, ProtocolLib, InventoryRollback, MVdWPlaceholderAPI, VotingPlugin, FastAsyncWorldEdit, DeluxeMenus, PermissionsEx, MOTDgdCommandAd, FeatherBoard, mcMMO, Vault, EpicRename, HolographicDisplays, VoteParty, AuctionHouse, ASkyBlock, TradePlus, Warps, MyCommand, CratesPlus, WorldEdit, CustomEnderChest, Essentials, HeadDatabase, LiteBans, Multiverse-Core, Citizens, BankNote, EssentialsChat, BattleLevels, IslandRate, ASkyBlock-IslandBorder, CustomOreGen, WorldGuard, LockettePro, EssentialsProtect, EssentialsGeoIP, EssentialsSpawn, AutoRide, CombatTagPlus, WildStacker, ShopGUIPlus, IslandTop, WildTools

**Description of issue. What happened?**

So when i make an /timings test to see why there is kinda lagg on the server it is saying "Skyblock - tickEntities" pct tick 98% percent, i thought it was due the config alot of checking spam but i couldnt find anything so i make ticket

**Steps to make this happen**

1. run server
2. play
3. get more players online and more lagg and higher pct tick

**What do you think should happen?**

**Comment by justinbea** [comment]
thread closed not even a reaction but okay

**Comment by jenaus** [comment]
what do you mean?

**Comment by Poslovitch** [comment]
1. https://github.com/tastybento/ASkyBlock-Bugs-N-Features/blob/master/README.md
2. FAQ

😉
