### ISSUE TITLE
ASkyBlock NEVER load

### ISSUE THREAD

**Issue by Saraistupid** [tastybento/askyblockIssues#955]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Spigot 1.12.2
**Plugin version:**
3.0.9.4
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
new install

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
Plugins (37): PermissionsEx, ViaVersion, Essentials, UnlimitedPlugins, PlaceholderAPI, ProtocolLib, Multiverse-Core, WorldEdit, WorldGuard, Parkour, EssentialsXMPP, BountifulAPI, MergedMob, HolographicDisplays, IslandBorder, EssentialsProtect, CClearChat, EssentialsGeoIP, LWC, Vault, BestViewDistance, MergedSpawner, EmojiChat, PingPlayer, AuctionHouse, HolographicExtension, DiscordSRV, Skript, Votifier, BuycraftX, SuperbVote, Citizens, EssentialsSpawn, EssentialsAntiBuild, SuperVanish, FurnaceLevels, EssentialsChat

**Description of issue. What happened?**
ASkyBlock dosen't load 
some times it is and some times it's not 
i tried the next:
REDOWNLOADING the plugin
RESTARTING the server
INSTALLING Vault over and over
it shows that error in console 
Could not load 'plugins/askyblock.jar' in folder 'plugins'

org.bukkit.plugin.UnknownDependencyException: Vault

at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:216) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
**Steps to make this happen**

1. 
2.
3.

**What do you think should happen?**

**Comment by Poslovitch** [comment]
That's Bukkit, not ASB

**Comment by Saraistupid** [comment]
mm ok?
then how i can fix this?
 cuz i'm bored to restart the server 500 times to make it work

**Comment by Poslovitch** [comment]
I cannot help. The only thing I know is that, it is not related to ASB

**Comment by Saraistupid** [comment]
ok

**Comment by Saraistupid** [comment]
thanks anyway
