### ISSUE TITLE
Another player uses a water bucket on another island.

### ISSUE THREAD

**Issue by yo-rin** [tastybento/askyblockIssues#962]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Spigot 1.12.2
**Plugin version: 3.0.9.4

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**

**Description of issue. What happened?**
Another player uses a water bucket on another island.
**Steps to make this happen**

1. go to another island
2. have water bucket
3. place on water bucket

**What do you think should happen?**
Another user don't uses a water bucket on another island.

**Comment by jenaus** [comment]
resolved the issue thank you. I could not find this report to change it.
Please let me know when Acid island and Bskyblock are going to be ready.

**Comment by Poslovitch** [comment]
BentoBox is already available at https://bentobox.world
